# Perfil de produção — PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mindflow
spring.datasource.username=mindflow
spring.datasource.password=mindflow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
